name: Roblox Tracker Bot
on:
  schedule:
    - cron: '*/5 * * * *' # รันทุก 5 นาที (เสถียรกว่า 1 นาทีบน GitHub แพลนฟรี)
  workflow_dispatch: # ปุ่มกดรันเอง

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Execute Tracker
        run: python script.py

      - name: Sync History
        run: |
          git config --global user.name 'AxelTrackerBot'
          git config --global user.email 'bot@axelhub.og'
          touch last_hash.txt last_future_hash.txt
          git add last_hash.txt last_future_hash.txt
          # ตรวจสอบก่อน commit ว่ามีอะไรเปลี่ยนไหม
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "update: sync history [skip ci]"
            git pull --rebase origin main # ดึงข้อมูลล่าสุดมาก่อนกัน Error
            git push origin main
          fi
